spring.application.name=Spring_Boot_Olympische_Spelen
## MySQL
spring.datasource.url=jdbc:mysql://localhost:3306/olympischespelen?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=Jafov.S9

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

##zelfde als drop and create
spring.jpa.hibernate.ddl-auto=create-drop
#spring.jpa.hibernate.ddl-auto=create
#spring.jpa.hibernate.ddl-auto=none
spring.messages.basename=i18n/messages
server.servlet.session.tracking-modes=COOKIE
logging.level.org.springframework.boot=INFO
